# Generated by Django 6.0.7 on 2026-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'training_session'), name='unique_user_session'),
        ),
    ]
