# Generated by Django 6.0.7 on 2026-07-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_reservation_unique_user_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['last_name', 'first_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['start_time', 'id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
